version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: 'daily'
  - package-ecosystem: 'docker'
    # Look for a Dockerfile in the root directory
    directory: '/'
    schedule:
      interval: 'daily'
