version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: 'daily'
  # Docker checks don't work recursively, so list both directories.
  - package-ecosystem: 'docker'
    directory: '/action-a'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/python-action'
    schedule:
      interval: 'daily'
