name: Workflow for my Hello World action
on: push

jobs:
  build:
    name: Hello World action
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Check Python paths
        run: |
          for p in python python3 /usr/bin/python3; do
              if which ${p}; then
                  ${p} --version
              fi
          done
      - name: show event type
        run: echo ${{ github.event_name }}
      - uses: ./action-a
        with:
          MY_NAME: 'Mona'
      - uses: ./python-action
        id: tripleadd
        with:
          NUM1: 1
          NUM2: 2
          NUM3: 4
      - run: |
          echo "Triple-Add reports: ${{ steps.tripleadd.outputs.sum }}"
      - uses: ./composite-action
        id: doubleadd
        with:
          num1: 1
          num2: 4
      - run: |
          echo "Double-Add reports: ${{ steps.doubleadd.outputs.sum }}"
      - name: Test color output
        run: |
          print('\u001b[31mHello Red\u001b[0m')
          print('\u001b[32mHello Green\u001b[0m')
        shell: python3 {0}
      - name: set name var
        run: echo "name=luna" >>${GITHUB_ENV}
      - name: condition with string formatting
        if: github.actor == format('airtower-{0}', env.name)
        run: echo "true"

  call-test:
    uses: airtower-luna/hello-github-actions/.github/workflows/reusable-echo.yaml@main
    with:
      test: |
        Hello World!
