name: Workflow for my Hello World action
on: push

jobs:
  build:
    name: Hello World action
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./action-a
        with:
          MY_NAME: 'Mona'
      - uses: ./python-action
        id: tripleadd
        with:
          NUM1: 1
          NUM2: 2
          NUM3: 4
      - run: |
          echo "Triple-Add reports: ${{ steps.tripleadd.outputs.sum }}"
      - uses: ./composite-action
        id: doubleadd
        with:
          num1: 1
          num2: 4
      - run: |
          echo "Double-Add reports: ${{ steps.doubleadd.outputs.sum }}"
