name: Reusable echo example with input

on:
  workflow_call:
    inputs:
      test:
        required: true
        type: string

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.test }}"
