name: Secret testing
on: push

jobs:
  check-secret:
    runs-on: ubuntu-latest
    outputs:
      secret_present: ${{ steps.secret.outputs.secret_present }}
    steps:
      - name: Check secret presence
        id: secret
        run: |
          if [ -n "${{ secrets.TEST_SECRET }}" ]; then
              echo "::set-output name=secret_present::true"
          else
              echo "::set-output name=secret_present::false"
          fi

  show-output:
    runs-on: ubuntu-latest
    needs: check-secret
    steps:
      - name: Show output of check-secret
        run: |
          echo "secret_present: ${{ needs.check-secret.outputs.secret_present }}"

  use-secret:
    runs-on: ubuntu-latest
    needs: check-secret
    if: needs.check-secret.outputs.secret_present == 'true'
    steps:
      - name: Show secret stats
        run: |
          echo "${{ secrets.TEST_SECRET }}" | wc

  template-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: replace placeholder using sed
        run: |
          sed -e 's,@TEST_SECRET@,${{ secrets.TEST_SECRET }},' test.json.in >test-sed.json
      - name: show result
        run: cat test-sed.json
      - name: set field in JSON
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        shell: python3 {0}
        run: |
          import json
          import os
          with open('test.json.in') as fh:
            data = json.load(fh)
          data['secret'] = os.environ['TEST_SECRET']
          with open('test-field.json', 'w') as fh:
            json.dump(data, fh)
      - name: show result
        run: cat test-field.json
