name: Wiki automation test
on: push

jobs:
  test:
    name: Wiki access
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
      - run: ls -al
      - run: cat Home.md
